version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_db
    ports:
      - "3306:3306"
    volumes:
      # Sử dụng đường dẫn tuyệt đối hoặc cụ thể để tránh lạc mất dữ liệu
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - social-network

  social-be:
    image: ${DOCKER_HUB_USERNAME}/social-be:latest
    container_name: social-be
    restart: always
    ports:
      - "8080:9090" # Khuyên dùng 8080 cho cả trong lẫn ngoài cho đỡ nhầm
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # Thêm param autoReconnect và createDatabaseIfNotExist
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/social_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JAVA_OPTS=-Xms512m -Xmx1024m
    depends_on:
      - mysql
    networks:
      - social-network
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

  social-fe:
    image: ${DOCKER_HUB_USERNAME}/social-fe:latest
    container_name: social-fe
    restart: always
    ports:
      - "80:5173"
    networks:
      - social-network

networks:
  social-network:
    driver: bridge