version: '3.8'

services:
  social-fe:
    image: ${DOCKER_IMAGE_FE}
    container_name: social-fe
    restart: always
    # Dùng mạng Host để tránh lỗi kết nối (giống Backend)
    network_mode: "host"    # Port 5173 sẽ được mở trực tiếp trên Host