pipeline {
    agent any

    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'develop', description: 'Nhánh code cần build (ví dụ: main, develop)')
    }
    
    environment {
        // Thông tin Image
        DOCKER_IMAGE = 'khanksky/social-fe'
        DOCKER_TAG = 'latest'
        DOCKER_CRED_ID = 'docker-hub-credentials'
        
        // Thông tin Server Deploy
        APP_SERVER_IP = '159.223.76.30'
        APP_SERVER_USER = 'root'
        DEPLOY_DIR = '/app/social'
        
        // Biến môi trường cho Frontend (API URL)
        // IP của server mới
        VITE_API_BASE_URL = 'http://159.223.76.30:8080/api'
    }
    
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    echo '=== Building Docker Image ==='
                    dir('social-fe') {
                        // Truyền biến build-arg vào
                        dockerImage = docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}", "--build-arg VITE_API_BASE_URL=${VITE_API_BASE_URL} .")
                    }
                }
            }
        }
        
        stage('Push to Docker Hub') {
            steps {
                script {
                    echo '=== Pushing to Docker Hub ==='
                    docker.withRegistry('', DOCKER_CRED_ID) {
                        dockerImage.push()
                    }
                }
            }
        }
        
        stage('Deploy to App Server') {
            steps {
                echo '=== Deploying to App Server ==='
                sshagent(['app-server-ssh-key']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ${APP_SERVER_USER}@${APP_SERVER_IP} '
                            cd ${DEPLOY_DIR}
                            # Pull image mới nhất
                            docker pull ${DOCKER_IMAGE}:${DOCKER_TAG}
                            
                            # Restart container FE
                            export DOCKER_HUB_USERNAME=khanksky
                            docker compose up -d --no-deps social-fe
                        '
                    """
                }
            }
        }
    }
}
