filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/application/logs/social-be.log

    # Gộp các dòng không bắt đầu bằng '{' vào dòng trước (stacktraces)
    multiline.pattern: '^\{'
    multiline.negate: true
    multiline.match: after
    scan_frequency: 5s

# Không để Filebeat tự decode JSON ở client để tránh lỗi khi file chứa text + JSON mix.
# Nếu muốn decode JSON ở client, tất cả dòng trong log phải là JSON thuần.

output.logstash:
  hosts: ["logstash:5044"]
  ssl.enabled: false

setup.kibana:
  host: "kibana:5601"