filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/application/logs/social-be.log
    json.keys_under_root: true
    json.add_error_key: true
    scan_frequency: 5s

output.logstash:
  hosts: ["logstash:5044"]
  ssl.enabled: false

setup.kibana:
  host: "kibana:5601"